# Generated by Django 5.2.17 on 2026-08-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_datos_movil', models.FloatField(default=0)),
                ('consumo_wifi', models.FloatField(default=0)),
                ('consumo_total', models.FloatField(default=0)),
                ('fecha', models.DateTimeField()),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado')], default='diario', max_length=30)),
                ('fuente', models.CharField(choices=[('ANDROID', 'Android'), ('OPERADOR', 'Operador')], default='ANDROID', max_length=20)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='dispositivos.dispositivo')),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='sims.sim')),
            ],
        ),
    ]
