# Generated by Django 5.2.17 on 2026-08-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('operadores', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('iccid', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=50, null=True)),
                ('mcc', models.CharField(blank=True, max_length=10)),
                ('mnc', models.CharField(blank=True, max_length=10)),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('sim_datos', models.BooleanField(default=False)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sims', to='operadores.operador')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sims_asignadas', to='dispositivos.dispositivo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sims_asignadas', to='trabajadores.trabajador')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='sims.sim')),
            ],
        ),
    ]
