# Generated by Django 5.2.17 on 2026-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0002_sim_monitoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
