# Generated by Django 5.2.17 on 2026-09-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_credencialdispositivo'),
        ('sims', '0003_sim_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sims', to='dispositivos.dispositivo'),
        ),
    ]
