# Generated by Django 5.2.17 on 2026-08-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_total', models.BigIntegerField(default=0)),
                ('ram_usada', models.BigIntegerField(default=0)),
                ('ram_disponible', models.BigIntegerField(default=0)),
                ('porcentaje', models.FloatField(default=0)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ram', to='dispositivos.dispositivo')),
            ],
        ),
    ]
