# Generated by Django 5.2.17 on 2026-08-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fabricante', models.CharField(blank=True, max_length=120, null=True)),
                ('modelo', models.CharField(blank=True, max_length=120, null=True)),
                ('version_android', models.CharField(blank=True, max_length=50, null=True)),
                ('android_sdk', models.IntegerField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('imei_1', models.CharField(blank=True, max_length=255, null=True)),
                ('imei_2', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_total', models.BigIntegerField(blank=True, null=True)),
                ('almacenamiento_total', models.BigIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_asignados', to='trabajadores.trabajador')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='dispositivos.dispositivo')),
            ],
        ),
    ]
