# Generated by Django 5.2.17 on 2026-08-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('operadores', '0001_initial'),
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conexion', models.CharField(choices=[('WIFI', 'WiFi'), ('DATOS_MOVILES', 'Datos Móviles'), ('SIN_CONEXION', 'Sin conexión')], default='WIFI', max_length=30)),
                ('ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('frecuencia', models.IntegerField(blank=True, null=True)),
                ('velocidad', models.FloatField(blank=True, null=True)),
                ('tipo_red_movil', models.CharField(blank=True, max_length=80, null=True)),
                ('ip_local', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_publica', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_red', to='dispositivos.dispositivo')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_red', to='operadores.operador')),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_red', to='sims.sim')),
            ],
        ),
    ]
