# Generated by Django 5.2.17 on 2026-08-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('CARGANDO', 'Cargando'), ('DESCARGANDO', 'Descargando'), ('CARGADA', 'Cargada'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=30)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_bateria', to='dispositivos.dispositivo')),
            ],
        ),
    ]
