# Generated by Django 5.2.17 on 2026-09-02 19:16

import usuarios.models
from django.db import migrations, models


def create_admin_role(apps, schema_editor):
    Rol = apps.get_model('usuarios', 'Rol')
    Rol.objects.get_or_create(
        nombre='ADMIN',
        defaults={'descripcion': 'Acceso administrativo configurable.', 'activo': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.JSONField(default=usuarios.models.default_permisos),
        ),
        migrations.RunPython(create_admin_role, migrations.RunPython.noop),
    ]
